name: ml-pipeline-framework
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python>=3.8
  
  # Core data processing
  - pandas>=1.5.0
  - numpy>=1.21.0
  - polars>=0.18.0
  - duckdb>=0.8.0
  - pyarrow>=9.0.0
  
  # Machine learning core
  - scikit-learn>=1.2.0
  - xgboost>=1.7.0
  - lightgbm>=3.3.0
  - catboost>=1.1.0
  - imbalanced-learn>=0.9.0
  
  # Model interpretability
  - shap>=0.41.0
  - lime>=0.2.0
  
  # Big data processing
  - pyspark>=3.3.0
  - dask>=2022.0.0
  
  # Configuration and utilities
  - pyyaml>=6.0
  - python-dotenv>=0.20.0
  - click>=8.1.0
  - tqdm>=4.64.0
  - requests>=2.28.0
  
  # Monitoring and logging
  - mlflow>=2.0.0
  - structlog>=22.0.0
  
  # Web framework
  - fastapi>=0.85.0
  - uvicorn>=0.18.0
  - pydantic>=1.10.0
  
  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.10.0
  - ipywidgets>=8.0.0
  
  # Hyperparameter optimization
  - optuna>=3.0.0
  
  # Data validation
  - great-expectations>=0.15.0
  
  # Database connectors
  - sqlalchemy>=1.4.0
  - psycopg2>=2.9.0
  - pymysql>=1.0.0
  - redis-py>=4.3.0
  
  # Performance
  - joblib>=1.2.0
  - numba>=0.56.0
  
  # Security
  - cryptography>=37.0.0
  - pyjwt>=2.4.0
  
  # Development tools
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-xdist>=3.0.0
  - pytest-mock>=3.0.0
  - black>=22.0.0
  - isort>=5.0.0
  - flake8>=5.0.0
  - mypy>=1.0.0
  - pre-commit>=2.0.0
  
  # Documentation
  - sphinx>=5.0.0
  - sphinx-rtd-theme>=1.0.0
  
  # Jupyter
  - jupyter>=1.0.0
  - jupyterlab>=3.4.0
  - ipykernel>=6.15.0
  
  # pip dependencies (packages not available in conda)
  - pip>=22.0.0
  - pip:
    # H2O AutoML
    - h2o>=3.38.0
    
    # Additional interpretability
    - eli5>=0.13.0
    
    # Specialized connectors
    - snowflake-connector-python>=3.0.0
    - pyhive>=0.6.5
    
    # Advanced optimization
    - hyperopt>=0.2.7
    - scikit-optimize>=0.9.0
    
    # Cloud and deployment
    - kubernetes>=24.0.0
    - docker>=6.0.0
    - boto3>=1.24.0
    - google-cloud-storage>=2.5.0
    - azure-storage-blob>=12.12.0
    
    # Data validation
    - cerberus>=1.3.0
    - marshmallow>=3.17.0
    
    # Monitoring
    - wandb>=0.13.0
    - prometheus-client>=0.16.0
    
    # Additional utilities
    - hydra-core>=1.2.0
    - omegaconf>=2.2.0
    - packaging>=21.0.0
    - importlib-metadata>=4.0.0
    - urllib3>=1.26.0
    
    # Development tools
    - pytest-timeout>=2.0.0
    - pytest-benchmark>=4.0.0
    - bandit>=1.7.0
    - safety>=2.0.0